---
# tasks file for wordpress

- include_tasks: yum.yml
  tags: [always]

- include_tasks: php.yml
  tags: [always]

- include_tasks: wordpress.yml
  tags: [always]

- include_tasks: exporter.yml
  tags: [always]
