---
# handlers file for gitlab
- name: Reload daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start postfix
  become: true
  ansible.builtin.systemd:
    name: postfix
    state: started
    enabled: yes

- name: Restart postfix
  become: true
  ansible.builtin.systemd:
    name: postfix
    state: restarted
    enabled: yes

- name: Start node_exporter
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Restart node_exporter
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted

- name: Restart gitlab
  become: true
  command: 'gitlab-ctl restart'
