---
- name: Stack Provisioning
  hosts: all
  tasks:

  - name: Firewall - Stop SELinux
    shell: setenforce 0

  - name: Firewall - Disable SELinux
    ansible.posix.selinux:
      state: disabled

  - name: Firewall - Stop Firewalld
    ansible.builtin.systemd:
      name: firewalld
      enabled : no
      masked: yes
      state: stopped

  - name: Files - Copy file Hosts
    ansible.builtin.copy:
      src: hosts
      dest: /etc/hosts

  - name: Hosts - Rename Hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Yum - Upgrade packages
    become: true
    yum:
      name: "*"
     enablerepo: base,updates,extras
      state: latest
      update_cache: yes


- name: MySQL Provisioning
  hosts: mysql
  roles:
    - mysql

- name: Wordpress Provisioning
  hosts: wordpress
  roles:
    - wordpress

- name: Monitoring Provisioning
  hosts: monitoring
  roles:
    - monitoring

- name: Nginx Provisioning
  hosts: nginx
  roles:
    - nginx

- name: GitLab Provisioning
  hosts: gitlab
  roles:
    - gitlab
