---

- name: PHP - Copy config file
  become: true
  ansible.builtin.template:
    src: www.conf.j2
    dest: "{{ fpm_path }}/www.conf"
    mode: '644'
  tags: wordpress

- name: PHP - Change group permission
  become: true
  ansible.builtin.file:
    path: "{{ php_path }}"
    state: directory
    recurse: yes
    group: nginx
  notify:
    - Restart php-fpm
  tags: wordpress

- name: Flush handlers
  meta: flush_handlers 

