---
# vars file for nginx

# yum.yml
repo_path: "/etc/yum.repos.d"

# nginx.yml
conf_path: "/etc/nginx/conf.d"

# letsencrypt.yml
wildcard_domain: "*.mooo.com"
email: "dim_id_roll@mail.ru"
dh_path: "/etc/ssl/certs"

# exporter.yml
arch: "linux-amd64"
bin_path: "/usr/local/bin"
tmp_path: "/tmp"
node_exporter_version: "1.3.1"
node_exporter_archive: "{{ tmp_path }}/node_exporter-{{ node_exporter_version }}.{{ arch }}.tar.gz"
node_exporter_path_tmp: "{{ tmp_path }}/node_exporter-{{ node_exporter_version }}.{{ arch }}"
systemd_path: "/etc/systemd/system"

# templates

server_name_alertmanager: ""
server_name_gitlab: ""
server_name_grafana: ""
server_name_prometheus: ""
server_name_www: ""

ip_upstream_alertmanager: ""
ip_upstream_gitlab: ""
ip_upstream_grafana: ""
ip_upstream_prometheus: ""
ip_upstream_www: ""
