---
#- name: MySQL Provisioning
#  hosts: mysql
#  roles:
#    - mysql

#- name: Wordpress Provisioning
#  hosts: wordpress
#  roles:
#    - wordpress

- name: Monitoring Provisioning
  hosts: monitoring
  roles:
    - monitoring

#- name: Nginx Provisioning
#  hosts: nginx
#  roles:
#    - nginx

#- name: GitLab Provisioning
#  hosts: gitlab
#  roles:
#    - gitlab
