---
nginx:
  hosts:
    nginx-01:
      ansible_host: 10.20.100.150
      ansible_ssh_user: netology

mysql:
  hosts:
    db1:
      ansible_host: 10.20.100.151
      ansible_ssh_user: netology
    db2:
      ansible_host: 10.20.100.152
      ansible_ssh_user: netology

wordpress:
  hosts:
    app:
      ansible_host: 10.20.100.153
      ansible_ssh_user: netology

gitlab:
  hosts:
    gitlab-01:
      ansible_host: 10.20.100.154
      ansible_ssh_user: netology
    runner-01:
      ansible_host: 10.20.100.155
      ansible_ssh_user: netology
monitoring:
  hosts:
    monitoring-01:
      ansible_host: 10.20.100.156
      ansible_ssh_user: netology
