- name: Stack Provisioning
  hosts: netology
  tasks:

#
  - name: Firewall - Stop SELinux
    shell: setenforce 0

  - name: Firewall - Disable SELinux
    ansible.posix.selinux:
      state: disabled

  - name: Firewall - Stop Firewalld
    ansible.builtin.systemd:
      name: firewalld
      enabled : no
      masked: yes
      state: stopped

#
  - name: Files - Copy file Hosts
    ansible.builtin.copy:
      src: hosts
      dest: /etc/hosts

#
  - name: Hosts - Rename Hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

#
  - name: Proxy - Edit /etc/profile
    blockinfile:
      path: /etc/profile
      block: |
        export HISTSIZE=10000
        export HISTTIMEFORMAT="%h %d %H:%M:%S "
        PROMPT_COMMAND='history -a'
        export HISTIGNORE="ls:ll:history:w:htop:pwd"

#
  - name: Yum - Upgrade packages
    become: true
    yum:
      name: "*"
      enablerepo: base,updates,extras
      state: latest
      update_cache: yes

  - name: Yum - Install packages
    become: true
    yum:
      name: 
        - wget
        - curl
        - tcpdump
        - mlocate
        - sysstat
        - nano
        - net-tools
        - zip
        - unzip
        - tar
        - bind-utils        
        - rsync
        - python-setuptools
        - python3
        - python3-pip
        - python3-setuptools
      enablerepo: base,updates,extras
      state: latest
