---

- name: LetsEncrypt - Install EPEL
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
    state: latest
  tags: nginx

- name: LetsEncrypt - Install Certbot for Nginx
  become: true
  ansible.builtin.yum:
    name:
      - certbot-nginx
    enablerepo: epel
    state: latest
  tags: nginx

- name: LetsEncrypt - Generate cert
  become: true
  command: 'certbot --nginx -d {{ wildcard_domain }} --test-cert --non-interactive --agree-tos -m {{ email }}'
  tags: nginx

- name: LetsEncrypt - Generate dhparam 2048
  community.crypto.openssl_dhparam:
    path: "{{ dh_path }}/dhparams.pem"
    size: 2048
  tags: nginx

#add dh param to nginx configs
#ssl_dhparam /etc/ssl/certs/dhparam.pem; to /etc/nginx/nginx.conf

- name: LetsEncrypt - Edit Crontab 
  become: yes
  ansible.builtin.cron:
    user: "root"
    name: "certbot autorenew"
    hour: "0"
    minute: "10"
    job: "/usr/bin/certbot renew --quiet"
    state: present
  tags: nginx
