---

- name: GitLab CE - Replace external url
  become: true
  ansible.builtin.replace:
    path: "{{ gitlab_conf }}"
    regexp: external_url 'http://gitlab.example.com'
    replace: external_url 'http://{{ gitlab_ip }}'
  tags: gitlab

- name: Update GitLab Config
  become: yes
  ansible.builtin.lineinfile:
    dest: "{{ gitlab_conf }}"
    line: "{{ item }}"
  with_items:
    - gitlab_rails['initial_root_password'] = "{{ gitlab_root_password }}"
    - gitlab_rails['initial_shared_runners_registration_token'] = "{{ gitlab_registration_token }}"
  tags: gitlab

- name: GitLab CE - Reconfigure
  become: true
  command: 'gitlab-ctl reconfigure'
  notify:
    - Restart gitlab
  tags: gitlab

- name: Flush handlers
  meta: flush_handlers
