---
# tasks file for gitlab

- name: SSH - Create keys
  ansible.builtin.user:
    name: netology
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

#- include: centos.yml
#  when: ansible_os_family == "Redhat"

- include_tasks: yum_gitlab.yml
  when:
    inventory_hostname == "gitlab-01"
  tags: [always]

- include_tasks: gitlab.yml
  when:
    inventory_hostname == "gitlab-01"
  tags: [always]

- include_tasks: yum_runner.yml
  when:
    inventory_hostname == "runner-01"
  tags: [always]

- include_tasks: runner.yml
  when:
    inventory_hostname == "runner-01"
  tags: [always]

- include_tasks: exporter.yml
  tags: [always]

- include_tasks: pipeline.yml
  when:
    inventory_hostname == "gitlab-01"
  tags: [always]


