---

- name: Pipeline - Install gitlab module
  become: true
  ansible.builtin.pip:
    name:
      - python-gitlab
    executable: pip3
  tags: gitlab

- name: Secure Install - Copy shell-script for root
  become: true
  ansible.builtin.template:
    src: script_root.sh.j2
    dest: "{{ tmp_path }}/script_root.sh"
    mode: '755'
  tags: gitlab

- name: Pipeline - Create API token for root
  become: true
  command: "{{ tmp_path }}/script_root.sh"
  register: token
  tags: gitlab

- name: Pipeline - Add user Netology
  community.general.gitlab_user:
    api_url: "{{ gitlab_api_url }}"
    api_token: "{{ gitlab_api_token_root }}"
    name: "{{ gitlab_name }}"
    username: "{{ gitlab_username }}"
    password: "{{ gitlab_password }}"
    email: "{{ gitlab_email }}"
    confirm: "{{ gitlab_confirm }}"
    sshkey_name: "{{ gitlab_sshkey_name }}"
    sshkey_file: "{{ gitlab_sshkey_file }}"
    state: present
    access_level: "{{ gitlab_access_level }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tags: gitlab

- name: Secure Install - Copy shell-script for netology
  become: true
  ansible.builtin.template:
    src: script_netology.sh.j2
    dest: "{{ tmp_path }}/script_netology.sh"
    mode: '755'
  tags: gitlab

- name: Pipeline - Create API token for netology
  become: true
  command: "{{ tmp_path }}/script_netology.sh"
  register: token
  tags: gitlab

- name: Pipeline - Create Group
  community.general.gitlab_group:
    api_url: "{{ gitlab_api_url }}"
    api_token: "{{ gitlab_api_token_user }}"
    name: "{{ gitlab_group_name }}"
    path: "{{ gitlab_group_path }}"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tags: gitlab

- name: Pipeline - Create GitLab Project Wordpress
  community.general.gitlab_project:
    api_url: "{{ gitlab_api_url }}"
    api_token: "{{ gitlab_api_token_user }}"
    name: "{{ gitlab_project_name }}"
    group: "{{ gitlab_group_name }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tags: gitlab
