---

- name: GitLab Runner - Install python-gitlab module
  become: true
  ansible.builtin.pip:
    name:
      - python-gitlab
    executable: pip3
  tags: gitlab

- name: GitLab Runner - Register runner
  become: true
  command: |
    gitlab-runner register \
      --non-interactive \
      --url="http://{{ gitlab_ip }}" \
      --registration-token="{{ gitlab_registration_token }}" \
      --description="{{ runner_desc }}" \
      --executor="{{ runner_exec }}" \
      --ssh-host="{{ runner_ssh_host }}" \
      --ssh-port="{{ runner_ssh_port }}" \
      --ssh-user="{{ runner_ssh_user }}" \
      --ssh-password="{{ runner_ssh_password }}" \
      --ssh-identity-file="{{ runner_ssh_id }}" \
      --ssh-disable-strict-host-key-checking="{{ runner_ssh_host_key_check }}"
  tags: gitlab
