---

- name: Yum - Install packages
  become: true
  ansible.builtin.yum:
    name:
      - policycoreutils
      - postfix
    state: latest
  tags: gitlab

- name: Yum - Get Git Runner repo
  ansible.builtin.get_url:
    url: "{{ runner_url }}"
    dest: "{{ tmp_path }}/script.rpm.sh"
    mode: '0755'
  tags: gitlab

- name: Yum - Install Git Runner repo
  become: true
  ansible.builtin.command: "{{ tmp_path }}/script.rpm.sh"
  tags: gitlab

- name: Yum - Install GitLab Runner
  become: true
  ansible.builtin.yum:
    name:
      - gitlab-runner
    state: latest
  tags: gitlab
